- name: Enable SYN PoW at Server Ingress
  hosts: syn_pow_verifier
  tasks:
    - name: setup tc qdisc
      shell: "{{ user_dir }}/common/ebpf/bin/tc_setup"
      register: result
      failed_when: result.rc != 0 and "cannot modify" not in result.stderr
      become: yes
    - name: re-compile and re-attach eBPF program
      shell: "{{ user_dir }}/common/mitigations/syn_pow_ingress.sh 1 {{ syn_pow_k }}"

- name: Enable SYN PoW at Client Egress
  hosts: active_clients
  tasks:
    - name: setup tc qdisc
      shell: "{{ user_dir }}/common/ebpf/bin/tc_setup"
      register: result
      failed_when: result.rc != 0 and "cannot modify" not in result.stderr
      become: yes
    - name: re-compile and re-attach eBPF program
      shell: "{{ user_dir }}/common/mitigations/syn_pow_egress.sh 1 {{ syn_pow_k }}"

- name: Enable SYN PoW at Attacker Egress
  hosts: active_attackers
  tasks:
    - name: setup tc qdisc
      when: attackers_do_mitigation == 1
      shell: "{{ user_dir }}/common/ebpf/bin/tc_setup"
      register: result
      failed_when: result.rc != 0 and "cannot modify" not in result.stderr
      become: yes
    - name: re-compile and re-attach eBPF program
      when: attackers_do_mitigation == 1
      shell: "{{ user_dir }}/common/mitigations/syn_pow_egress.sh 1 {{ syn_pow_k }}"