- name: Enable SYN Padding at Server Ingress
  hosts: syn_pow_verifier
  tasks:
    - name: setup tc qdisc
      shell: "{{ user_dir }}/common/ebpf/bin/tc_setup"
      register: result
      failed_when: result.rc != 0 and "cannot modify" not in result.stderr
      become: yes
    - name: re-compile and re-attach eBPF program
      shell: "{{ user_dir }}/common/mitigations/syn_pad_ingress.sh 1"

- name: Enable SYN PoW at Client Egress
  hosts: active_clients
  tasks:
    - name: setup tc qdisc
      shell: "{{ user_dir }}/common/ebpf/bin/tc_setup"
      register: result
      failed_when: result.rc != 0 and "cannot modify" not in result.stderr
      become: yes
    - name: re-compile and re-attach eBPF program
      shell: "{{ user_dir }}/common/mitigations/syn_pad_egress.sh 1"