- hosts: all
  tasks:
  - name: check kernel version
    shell: uname -r
    register: kernel_version

  - name: install eBPF dependencies
    apt:
      name: gcc, gcc-multilib, clang, llvm, linux-tools-common, linux-tools-generic, linux-tools-{{ kernel_version.stdout }}, libbpf-dev
      update_cache: yes
    become: yes

  - name: install general dependencies
    apt:
      name: net-tools, traceroute, tcpstat, ncat, cpulimit, bc
      update_cache: yes
    become: yes

- hosts: server
  tasks:
  - name: install server dependencies
    apt:
      name: apache2
    become: yes

- hosts: client
  tasks:
  - name: install client dependencies
    apt:
      name: cargo, cmake, git
      update_cache: yes
    become: yes

  - name: clone quiche repo
    git:
      repo: https://github.com/cloudflare/quiche
      dest: /usr/local/quiche

  - name: install quiche
    shell:
      cmd: cargo build --package quiche --release --features ffi,pkg-config-meta,qlog
      chdir: /usr/local/quiche
  
  - name: Create BoringSSL directory
    file:
      path: /usr/local/quiche/quiche/deps/boringssl/src/lib
      state: directory

  - name: Link libssl
    shell:
      cmd: ln -vnf $(find target/release -name libcrypto.a -o -name libssl.a) quiche/deps/boringssl/src/lib/
      chdir: /usr/local/quiche

  - name: clone curl repo
    git:
      repo: https://github.com/curl/curl
      dest: /usr/local/curl

  - name: build curl
    shell:
      cmd: autoreconf -fi
      chdir: /usr/local/curl

  - name: configure curl
    shell:
      cmd: ./configure LDFLAGS="-Wl,-rpath,$PWD/../quiche/target/release" --with-openssl=$PWD/../quiche/quiche/deps/boringssl/src --with-quic
      chdir: /usr/local/curl
      
  - name: make curl
    shell:
      cmd: make
      chdir: /usr/local/curl

  - name: install curl
    shell:
      cmd: make install
      chdir: /usr/local/curl
      become: yes

- import_playbook: "push_common.yml"
