- name: install nginx server
  hosts: server
  gather_facts: true
  tasks:
    - name: run server setup script
      shell: /usr/local/dos-mitigation/common/setup/quic_server_setup.sh
      become: no
    - name: create SSL certificate
      shell: /usr/local/dos-mitigation/common/setup/cert_gen.sh
      become: no
    - name: Delete old HTTP junk directory
      become: yes
      file:
        path: /var/www/html/junk
        state: absent
    - name: Recreate HTTP junk directory
      become: yes
      file:
        path: /var/www/html/junk
        state: directory
    - name: Create junk file for HTTP client
      shell: head -c 1G </dev/urandom >/var/www/html/junk.bin
      become: yes

- name: install curl client
  hosts: client, attacker
  gather_facts: true
  tasks:
    - name: run client setup script
      shell: /usr/local/dos-mitigation/common/setup/quic_client_setup.sh
      become: no
    - name: push server certificate
      synchronize:
        src: /usr/local/dos_mitigation/server.crt
        dest: /usr/local/nginx/certs/server.crt
        mode: push
      become: yes
    - name: test client-server connection
      shell: /usr/local/dos-mitigation/common/clients/http3_test.sh {{ server_name }} 1000